codeforpdx/tenantfirstaid

backend/pyproject.toml
backend/uv.lock

Resolves #19 and includes missing 'python-dotenv' dependency for the environment.
Before I crash out because it was missing the dependency:
Was able to boot up Flask after including `python-dotenv` in `pyproject.toml`:

[Bug] - Include missing dotenv dependency

---

.gitignore
backend/.env.example
backend/PERSISTENT_DATA_README.md
backend/tenantfirstaid/chat.py
backend/tenantfirstaid/shared.py

- Allow setting `PERSISTENT_STORAGE_DIR` in `.env` to specify a different storage directory than `/root`
- Allow other model endpoints than OpenAI (e.g. Github Models)

Feat: QoL improvements

---

frontend/src/Chat.tsx
frontend/src/pages/Chat/components/ExportMessagesButton.tsx
frontend/src/pages/Chat/utils/exportHelper.ts

This PR resolves #27 by including a simple button that triggers the export of the ongoing messages using the browser's native print functionality. From there, users can save it as a PDF. Further changes to the styling and location of the button can be decided when the Figma design is ready.
The type for Messages was also changed to IMessages to help differentiate between interfaces/types and components.

Feature: Export messages button

---

backend/pyproject.toml

Builds not working because of the new `data` directory added by local valkey setup. This change ignores the 'data' directory in setuptools.

fix: ignore data directory

---

frontend/src/AboutPage.tsx
frontend/src/App.tsx
frontend/src/Chat.tsx

PR to add the first version of an "About Us" page
- Added an "About Us" button to the homepage.
- Linked the button to the `/about` route.
- Created a basic About page component.
This is just the initial setup — it's currently unstyled and has placeholder content.  
More detailed content and styling will be added in a future update.
This establishes the structure so others can contribute to the About page layout and content.

Add about page

---

frontend/src/App.tsx
frontend/src/contexts/SessionContext.tsx
frontend/src/hooks/useSession.tsx
frontend/src/pages/Chat/components/InputField.tsx
frontend/src/pages/Chat/components/MessageFeedback.tsx
frontend/src/pages/Chat/components/MessageWindow.tsx

This PR resolves #64 and updates `sessionId` from using useState to React Context. Opens up the path for other potential contexts like notifications and messages. Also opens up the path for multiple sessions within the browser (e.g., storing a list of sessionIds for various chat sessions similar to ChatGPT)
Branch is built on top of PR #63. Can be merged after PR #63 to avoid a merge conflict

Move sessionid to React Context

---

frontend/src/Chat.tsx
frontend/src/pages/Chat/components/ExportMessagesButton.tsx
frontend/src/pages/Chat/components/MessageWindow.tsx

As the title suggest, this PR is for minor styling updates and refactoring of the Chat component.
The button to navigate to "about" is replaced with React Router's Link. The button to export the conversation also had its styling updated to match that of the link to "about". The spacing for existing components within Chat has been altered to make the display better for mobile.

Minor styling updates and refactoring for mobile

---

frontend/src/hooks/useMessages.tsx

This PR resolves #76 by patching up the bug related to the chat history. (See below)
https://github.com/user-attachments/assets/3c3c10a1-e17c-4b23-8df5-b768b465c51b
There seems to be a clash between how the data gets refetched from `addMessage` when mutated and how the chat history is fetched from `fetchChatHistory`, and removing `invalidateQueries` seems to fix the issue.

Bug Fix: Chat history sync issue

---

frontend/src/pages/Chat/components/MessageContent.tsx

Partially address #35 by adding interactivity to the ORS statutes that the AI generates. (see below)
https://github.com/user-attachments/assets/ee51c675-ef74-493e-a012-cf2667872cd8
The subcomponent called HighlightORS expects statutes with a general pattern of `ORS <statute number and letters>` and places them within an anchor tag. For the time being, clicking on it will route the user to the general statute at oregon.public.law.
In the future, we'll want to expand on this so that it'll open up a drawer/menu of sorts which would provide additional information based on that statute by hitting an API endpoint. The direct link could also be moved within the drawer/menu instead of the direct link from the chat.

Feature: Highlighting ORS Statutes from generated text

---

frontend/src/pages/Chat/components/Navbar.tsx
frontend/src/pages/Chat/components/StatuteDrawer.tsx

fixed an UI bug where the hamburger menu was behind the citation popup
https://github.com/user-attachments/assets/c78edcc0-b1e7-4884-859e-47a7a6adbc74

Adjust z-index for MessageWindow and Hamburger Menu

---

frontend/src/AboutPage.tsx
frontend/src/Chat.tsx
frontend/src/pages/Chat/components/ExportMessagesButton.tsx
frontend/src/pages/Chat/components/InputField.tsx
frontend/src/pages/Chat/components/MessageWindow.tsx
frontend/src/pages/Chat/components/Navbar.tsx
frontend/src/pages/Chat/components/StatuteDrawer.tsx
frontend/src/style.css

As discussed in today's meeting, I've begun migrating existing theme colors to what we have from our Figma boards. The changes to coloring include the Chat window, the About page, and the Navbar.
The main color palette used when updating the theme consists of the following colors:
The general coloring for existing utility buttons like Clear (#E3574B) and Export (#4A90E2) as well as for text highlighting for statutes remains untouched. The hover color for Export has been changed to a slightly darker hue to make the hover effect stand out more. (see visual changes below)
https://github.com/user-attachments/assets/61b99f04-b8e1-42ff-a803-81939e5ec7fc
Given that the message window utilizes #F4F4F2 as its background, I've opted to use #E2E8F0 to make the message from the bot stand out.
Other …

Update site theme colors

---

backend/tests/test_citations.py

coverage before ...
```
=== tests coverage ===
___ coverage: platform linux, python 3.12.3-final-0 ___
Name                          Stmts   Miss  Cover
-------------------------------------------------
tenantfirstaid/__init__.py        0      0   100%
tenantfirstaid/app.py            30      7    77%
tenantfirstaid/chat.py           63     44    30%
tenantfirstaid/citations.py      14      7    50%
tenantfirstaid/session.py        15      4    73%
tenantfirstaid/shared.py         11      0   100%
tests/test_import.py              4      0   100%
-------------------------------------------------
TOTAL                           137     62    55%
```
coverage after ...
```
=== tests coverage ===
___ coverage: platform linux, python 3.12.3-final-0 ___
Name                          Stmts …
```

Add test for citations.py

---

backend/pyproject.toml
backend/tests/test_session.py
backend/uv.lock

coverage before ...
```
=== tests coverage ===
___ coverage: platform linux, python 3.12.3-final-0 ___
Name                          Stmts   Miss  Cover
-------------------------------------------------
tenantfirstaid/__init__.py        0      0   100%
tenantfirstaid/app.py            30      7    77%
tenantfirstaid/chat.py           63     44    30%
tenantfirstaid/citations.py      14      7    50%
tenantfirstaid/session.py        15      4    73%
tenantfirstaid/shared.py         11      0   100%
tests/test_import.py              4      0   100%
-------------------------------------------------
TOTAL                           137     62    55%
```
coverage after ...
```
=== tests coverage ===
___ coverage: platform linux, python 3.12.3-final-0 ___
Name                          Stmts …
```

add test for session.py

---

backend/tenantfirstaid/session.py
backend/tests/test_session.py

I rewrote some of the tests for the new `session.py` logic, but I'm having problems with the last one (roundtrip set/get).  This is better than nothing.
There's a bunch of cut'n'paste from test to test.  Future work would be to refactor back into reusable fixtures.

some working tests but 1 is still broken

---

frontend/src/contexts/SessionContext.tsx
frontend/src/pages/Chat/components/CitySelectField.tsx

This PR provides minor updates to state management for `CitySelectField` by streamlining the number of states in the component. Functionality should be the same as before (see below).
https://github.com/user-attachments/assets/9e3330b2-3c06-4a79-85bd-020773927d9e
Other changes include removing browser reload from the try block for `handleNewSession` since the rendering of new session messages will be handled by the `initChat` function in `useMessages`. This would avoid additional re-renderings after clearing a chat session.

Enhancement: Update CitySelectField state management

---

frontend/src/About.tsx
frontend/src/App.tsx
frontend/src/Disclaimer.tsx
frontend/src/pages/Chat/components/Navbar.tsx
frontend/src/shared/components/BackLink.tsx

Resolves #125, this PR introduces a dedicated route for Disclaimer and includes the content suggested by @michaelzhang43.
https://github.com/user-attachments/assets/f0205aa6-f3c1-487a-9280-5a9cb90560ca
Other minor changes include changing buttons used for navigation into Links, refactoring the Back links into its own component under `src/shared/components`, and a minor layout update for the About page.
For the time being, there's a placeholder link to `Privacy Policy` which direct users back to this diclaimer page, but we'll be able to create a new page for that when Michael gets that portion ready.

Feature: Disclaimer Page

---

frontend/src/App.tsx
frontend/src/Disclaimer.tsx
frontend/src/PrivacyPolicy.tsx
frontend/src/pages/Chat/components/Navbar.tsx

Built on top of PR #126, this PR resolves #127 by including content for the site's Privacy Policy provided by @michaelzhang43 and adding a new route for the policy.
https://github.com/user-attachments/assets/474b9133-46df-4d77-87f6-f6640509e259
Requires #126 to merge first.

Feature: Privacy Policy Page

---

frontend/src/pages/Chat/components/InputField.tsx
frontend/src/pages/Chat/components/MessageWindow.tsx
frontend/src/pages/Chat/components/SuggestedPrompts.tsx

This PR resolves #142 by switching the existing `input` element for the input field with a `textarea`. This gives users more flexibility in typing and formatting their message before sending it to the chatbot. At the moment, the max height has been arbitrarily set to 88px. That can be changed in the future if needed.
https://github.com/user-attachments/assets/94cb9b1b-9298-4f5a-872d-70d55f417d75
The behavior used for resizing the textarea is similar to what OpenAI uses for ChatGPT. It keeps the messages in place at the same location while letting the text field expand.
https://github.com/user-attachments/assets/31a725d2-a844-46f9-81b4-165c801a2047
Other changes in this PR include a minor edit for the suggested prompt by adding a max size of 650px to make them stay within the 700px width …

Enhancement: Changing input field into textarea

---

.github/workflows/pr-check.yml

Merging a PR results in a push, but a push does not always imply a PR.  We want to know whether `main` is clean, regardless of how a change was made.

check on push to main branch and releases

---

backend/Makefile
backend/pyproject.toml
backend/scripts/create_vector_store.py
backend/tenantfirstaid/chat.py
backend/tenantfirstaid/session.py
backend/uv.lock

Previously the `typecheck-mypy` Makefile target focused on the `tenantfirstaid` package.  Added a new target to also check the `scripts` as well.
Addresses errors when running `make typecheck-pyrefly`.
Addresses some of the errors when running `make typecheck-mypy TYPECHECK_OPTIONS="--strict"`.  There are still a few that are related to Flask hooks (e.g. `jsonify()`, `dispatch_request()`) that I don't know how to handle (other than ignoring).
- Related Issue #
- Closes #
```sh
make check typecheck-mypy typecheck-pyrefly
```

Typecheck scripts too
